[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NUXT_PUBLIC_API_BASE = "https://cars-website-api-production.up.railway.app/"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"
