/**
 * Mapa nazwa ikony -> sciezka SVG.
 *
 * Wygenerowana ze skanu repozytoriow (frontend, a gdy lezy obok - takze backend,
 * bo nazwy ikon kategorii przychodza z bazy). Importy sa WYPISANE JAWNIE, nie przez
 * `import * as` - dzieki temu bundler dolacza wylacznie te 318 sciezek,
 * a nie caly zestaw 7447. To jest cala roznica miedzy ~8 kB
 * a ~400 kB w paczce wyslanej do przegladarki.
 *
 * NIE EDYTOWAC RECZNIE - plik odtwarza `npm run icons`.
 */
import {
    mdiAccountCheck,
    mdiAccountCheckOutline,
    mdiAccountCircle,
    mdiAccountCircleOutline,
    mdiAccountGroupOutline,
    mdiAccountKeyOutline,
    mdiAccountMultipleOutline,
    mdiAccountOffOutline,
    mdiAccountOutline,
    mdiAccountPlusOutline,
    mdiAccountRemove,
    mdiAccountTieOutline,
    mdiAccountWrench,
    mdiAlertCircle,
    mdiAlertCircleOutline,
    mdiAlertOutline,
    mdiApps,
    mdiArchiveArrowDown,
    mdiArchiveArrowUp,
    mdiArchiveOutline,
    mdiArrowLeft,
    mdiArrowRight,
    mdiArrowRightCircleOutline,
    mdiArrowRightThin,
    mdiArrowUpLeft,
    mdiAtv,
    mdiAutoFix,
    mdiBankOutline,
    mdiBarcode,
    mdiBarcodeOff,
    mdiBarcodeScan,
    mdiBell,
    mdiBellOffOutline,
    mdiBellOutline,
    mdiBookCheckOutline,
    mdiBookOpenOutline,
    mdiBookmarkCheckOutline,
    mdiBookmarkOutline,
    mdiBriefcaseOutline,
    mdiBroom,
    mdiBullhornOutline,
    mdiBus,
    mdiCalendar,
    mdiCalendarCheckOutline,
    mdiCalendarClock,
    mdiCalendarEnd,
    mdiCalendarMonth,
    mdiCalendarMultiple,
    mdiCalendarOutline,
    mdiCalendarPlusOutline,
    mdiCalendarRange,
    mdiCalendarRemove,
    mdiCalendarRemoveOutline,
    mdiCalendarStar,
    mdiCalendarStart,
    mdiCalendarWeek,
    mdiCancel,
    mdiCar,
    mdiCarClock,
    mdiCarCog,
    mdiCarCruiseControl,
    mdiCarDoor,
    mdiCarEstate,
    mdiCarInfo,
    mdiCarKey,
    mdiCarLightHigh,
    mdiCarMultiple,
    mdiCarOff,
    mdiCarOutline,
    mdiCarSearch,
    mdiCarSearchOutline,
    mdiCarSeat,
    mdiCarSettings,
    mdiCarShiftPattern,
    mdiCarSide,
    mdiCarSports,
    mdiCarTractionControl,
    mdiCarWash,
    mdiCarWrench,
    mdiCaravan,
    mdiCardAccountDetailsOutline,
    mdiCardTextOutline,
    mdiCash,
    mdiCashMultiple,
    mdiCashRefund,
    mdiCertificate,
    mdiCertificateOutline,
    mdiChartBar,
    mdiCheck,
    mdiCheckAll,
    mdiCheckCircle,
    mdiCheckCircleOutline,
    mdiCheckDecagram,
    mdiCheckDecagramOutline,
    mdiChevronDown,
    mdiChevronLeft,
    mdiChevronRight,
    mdiChevronUp,
    mdiCircleDouble,
    mdiCircleOutline,
    mdiCircleSmall,
    mdiClipboardCheckOutline,
    mdiClipboardListOutline,
    mdiClockAlertOutline,
    mdiClockOutline,
    mdiClockRemoveOutline,
    mdiClose,
    mdiCloseCircle,
    mdiCloseCircleOutline,
    mdiCloudSyncOutline,
    mdiCloudUploadOutline,
    mdiCog,
    mdiCogOffOutline,
    mdiCogOutline,
    mdiCogTransferOutline,
    mdiCompare,
    mdiCompareRemove,
    mdiContentCopy,
    mdiContentDuplicate,
    mdiContentSaveOutline,
    mdiCookieCogOutline,
    mdiCookieOutline,
    mdiCpu64Bit,
    mdiCrane,
    mdiCreditCardOffOutline,
    mdiCreditCardOutline,
    mdiCrown,
    mdiCrownOutline,
    mdiCurrencyUsd,
    mdiDatabaseCheckOutline,
    mdiDatabaseSearchOutline,
    mdiDeleteAlertOutline,
    mdiDeleteOutline,
    mdiDiamondOutline,
    mdiDomain,
    mdiDotsHorizontalCircle,
    mdiDotsHorizontalCircleOutline,
    mdiDotsVertical,
    mdiDownloadOutline,
    mdiDrag,
    mdiEarth,
    mdiEmailAlertOutline,
    mdiEmailArrowRightOutline,
    mdiEmailCheckOutline,
    mdiEmailFastOutline,
    mdiEmailMarkAsUnread,
    mdiEmailOutline,
    mdiEmailSyncOutline,
    mdiEngineOff,
    mdiEngineOffOutline,
    mdiEngineOutline,
    mdiExcavator,
    mdiExitRun,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiFacebook,
    mdiFacebookMessenger,
    mdiFactory,
    mdiFileAlertOutline,
    mdiFileCodeOutline,
    mdiFileDocumentOutline,
    mdiFileOutline,
    mdiFilePdfBox,
    mdiFileSearchOutline,
    mdiFileVideoOutline,
    mdiFilterRemoveOutline,
    mdiFilterVariant,
    mdiFire,
    mdiFlag,
    mdiFlagOffOutline,
    mdiFlagOutline,
    mdiForklift,
    mdiFormSelect,
    mdiFormatListBulleted,
    mdiFormatListCheckbox,
    mdiFuel,
    mdiFullscreen,
    mdiGarage,
    mdiGasStationOutline,
    mdiGiftOutline,
    mdiHandshakeOutline,
    mdiHardHat,
    mdiHeadset,
    mdiHeart,
    mdiHeartOutline,
    mdiHelpCircleOutline,
    mdiHistory,
    mdiHomeOutline,
    mdiIdentifier,
    mdiImageMultipleOutline,
    mdiImageOffOutline,
    mdiImageOutline,
    mdiImagePlusOutline,
    mdiImageSearchOutline,
    mdiImageSizeSelectLarge,
    mdiInformationOutline,
    mdiInstagram,
    mdiKeyAlertOutline,
    mdiKeyOutline,
    mdiLeaf,
    mdiLightbulbOnOutline,
    mdiLightbulbOutline,
    mdiLightningBolt,
    mdiLinkVariant,
    mdiLoading,
    mdiLockCheckOutline,
    mdiLockOpenOutline,
    mdiLockOutline,
    mdiLockReset,
    mdiLogin,
    mdiLogout,
    mdiMagnify,
    mdiMagnifyClose,
    mdiMapMarker,
    mdiMapMarkerOffOutline,
    mdiMapMarkerOutline,
    mdiMapOutline,
    mdiMapSearchOutline,
    mdiMessageOffOutline,
    mdiMessageOutline,
    mdiMessageTextOutline,
    mdiMinusCircleOutline,
    mdiMoleculeCo2,
    mdiMonitorSpeaker,
    mdiMotorbike,
    mdiMusicNote,
    mdiNumeric,
    mdiOfficeBuildingOutline,
    mdiOpenInNew,
    mdiPackageVariantClosed,
    mdiPaletteOutline,
    mdiPencil,
    mdiPencilOutline,
    mdiPhone,
    mdiPhoneAlertOutline,
    mdiPhoneCheckOutline,
    mdiPhoneOutline,
    mdiPin,
    mdiPinOff,
    mdiPlus,
    mdiPlusCircleOutline,
    mdiQrcode,
    mdiReceiptOutline,
    mdiReceiptTextCheckOutline,
    mdiReceiptTextOutline,
    mdiRecordCircleOutline,
    mdiRefresh,
    mdiRocketLaunchOutline,
    mdiRvTruck,
    mdiSailBoat,
    mdiSeatPassenger,
    mdiSeatReclineExtra,
    mdiSend,
    mdiSendOutline,
    mdiShapeOutline,
    mdiShapePlusOutline,
    mdiShareOutline,
    mdiShareVariantOutline,
    mdiShieldAccountOutline,
    mdiShieldAlertOutline,
    mdiShieldCar,
    mdiShieldCheck,
    mdiShieldCheckOutline,
    mdiShieldCrown,
    mdiShieldOutline,
    mdiShieldSearch,
    mdiShieldStarOutline,
    mdiSkiWater,
    mdiSort,
    mdiSpeedometer,
    mdiSpeedometerMedium,
    mdiSpray,
    mdiStar,
    mdiStarCheckOutline,
    mdiStarOffOutline,
    mdiStarOutline,
    mdiStoreOutline,
    mdiSwapHorizontal,
    mdiSync,
    mdiTag,
    mdiTagMultipleOutline,
    mdiTagOffOutline,
    mdiTagOutline,
    mdiTextBoxOutline,
    mdiTextBoxRemoveOutline,
    mdiTextLong,
    mdiTextSearch,
    mdiTicketOutline,
    mdiTicketPercentOutline,
    mdiTimerOutline,
    mdiTire,
    mdiTractor,
    mdiTransitConnectionVariant,
    mdiTranslate,
    mdiTrashCanOutline,
    mdiTrendingDown,
    mdiTrendingUp,
    mdiTrophyOutline,
    mdiTruck,
    mdiTruckDelivery,
    mdiTruckOutline,
    mdiTruckTrailer,
    mdiTuneVariant,
    mdiTwitter,
    mdiUnfoldLessHorizontal,
    mdiUnfoldMoreHorizontal,
    mdiUpload,
    mdiVanUtility,
    mdiViewDashboardOutline,
    mdiWarehouse,
    mdiWeb,
    mdiWeight,
    mdiWhatsapp,
    mdiWifiOff,
    mdiWrench,
    mdiWrenchClock,
    mdiWrenchOutline,
    mdiYoutube,
} from '@mdi/js'

export const MDI_PATHS: Record<string, string> = {
    'mdi-account-check': mdiAccountCheck,
    'mdi-account-check-outline': mdiAccountCheckOutline,
    'mdi-account-circle': mdiAccountCircle,
    'mdi-account-circle-outline': mdiAccountCircleOutline,
    'mdi-account-group-outline': mdiAccountGroupOutline,
    'mdi-account-key-outline': mdiAccountKeyOutline,
    'mdi-account-multiple-outline': mdiAccountMultipleOutline,
    'mdi-account-off-outline': mdiAccountOffOutline,
    'mdi-account-outline': mdiAccountOutline,
    'mdi-account-plus-outline': mdiAccountPlusOutline,
    'mdi-account-remove': mdiAccountRemove,
    'mdi-account-tie-outline': mdiAccountTieOutline,
    'mdi-account-wrench': mdiAccountWrench,
    'mdi-alert-circle': mdiAlertCircle,
    'mdi-alert-circle-outline': mdiAlertCircleOutline,
    'mdi-alert-outline': mdiAlertOutline,
    'mdi-apps': mdiApps,
    'mdi-archive-arrow-down': mdiArchiveArrowDown,
    'mdi-archive-arrow-up': mdiArchiveArrowUp,
    'mdi-archive-outline': mdiArchiveOutline,
    'mdi-arrow-left': mdiArrowLeft,
    'mdi-arrow-right': mdiArrowRight,
    'mdi-arrow-right-circle-outline': mdiArrowRightCircleOutline,
    'mdi-arrow-right-thin': mdiArrowRightThin,
    'mdi-arrow-up-left': mdiArrowUpLeft,
    'mdi-atv': mdiAtv,
    'mdi-auto-fix': mdiAutoFix,
    'mdi-bank-outline': mdiBankOutline,
    'mdi-barcode': mdiBarcode,
    'mdi-barcode-off': mdiBarcodeOff,
    'mdi-barcode-scan': mdiBarcodeScan,
    'mdi-bell': mdiBell,
    'mdi-bell-off-outline': mdiBellOffOutline,
    'mdi-bell-outline': mdiBellOutline,
    'mdi-book-check-outline': mdiBookCheckOutline,
    'mdi-book-open-outline': mdiBookOpenOutline,
    'mdi-bookmark-check-outline': mdiBookmarkCheckOutline,
    'mdi-bookmark-outline': mdiBookmarkOutline,
    'mdi-briefcase-outline': mdiBriefcaseOutline,
    'mdi-broom': mdiBroom,
    'mdi-bullhorn-outline': mdiBullhornOutline,
    'mdi-bus': mdiBus,
    'mdi-calendar': mdiCalendar,
    'mdi-calendar-check-outline': mdiCalendarCheckOutline,
    'mdi-calendar-clock': mdiCalendarClock,
    'mdi-calendar-end': mdiCalendarEnd,
    'mdi-calendar-month': mdiCalendarMonth,
    'mdi-calendar-multiple': mdiCalendarMultiple,
    'mdi-calendar-outline': mdiCalendarOutline,
    'mdi-calendar-plus-outline': mdiCalendarPlusOutline,
    'mdi-calendar-range': mdiCalendarRange,
    'mdi-calendar-remove': mdiCalendarRemove,
    'mdi-calendar-remove-outline': mdiCalendarRemoveOutline,
    'mdi-calendar-star': mdiCalendarStar,
    'mdi-calendar-start': mdiCalendarStart,
    'mdi-calendar-week': mdiCalendarWeek,
    'mdi-cancel': mdiCancel,
    'mdi-car': mdiCar,
    'mdi-car-clock': mdiCarClock,
    'mdi-car-cog': mdiCarCog,
    'mdi-car-cruise-control': mdiCarCruiseControl,
    'mdi-car-door': mdiCarDoor,
    'mdi-car-estate': mdiCarEstate,
    'mdi-car-info': mdiCarInfo,
    'mdi-car-key': mdiCarKey,
    'mdi-car-light-high': mdiCarLightHigh,
    'mdi-car-multiple': mdiCarMultiple,
    'mdi-car-off': mdiCarOff,
    'mdi-car-outline': mdiCarOutline,
    'mdi-car-search': mdiCarSearch,
    'mdi-car-search-outline': mdiCarSearchOutline,
    'mdi-car-seat': mdiCarSeat,
    'mdi-car-settings': mdiCarSettings,
    'mdi-car-shift-pattern': mdiCarShiftPattern,
    'mdi-car-side': mdiCarSide,
    'mdi-car-sports': mdiCarSports,
    'mdi-car-traction-control': mdiCarTractionControl,
    'mdi-car-wash': mdiCarWash,
    'mdi-car-wrench': mdiCarWrench,
    'mdi-caravan': mdiCaravan,
    'mdi-card-account-details-outline': mdiCardAccountDetailsOutline,
    'mdi-card-text-outline': mdiCardTextOutline,
    'mdi-cash': mdiCash,
    'mdi-cash-multiple': mdiCashMultiple,
    'mdi-cash-refund': mdiCashRefund,
    'mdi-certificate': mdiCertificate,
    'mdi-certificate-outline': mdiCertificateOutline,
    'mdi-chart-bar': mdiChartBar,
    'mdi-check': mdiCheck,
    'mdi-check-all': mdiCheckAll,
    'mdi-check-circle': mdiCheckCircle,
    'mdi-check-circle-outline': mdiCheckCircleOutline,
    'mdi-check-decagram': mdiCheckDecagram,
    'mdi-check-decagram-outline': mdiCheckDecagramOutline,
    'mdi-chevron-down': mdiChevronDown,
    'mdi-chevron-left': mdiChevronLeft,
    'mdi-chevron-right': mdiChevronRight,
    'mdi-chevron-up': mdiChevronUp,
    'mdi-circle-double': mdiCircleDouble,
    'mdi-circle-outline': mdiCircleOutline,
    'mdi-circle-small': mdiCircleSmall,
    'mdi-clipboard-check-outline': mdiClipboardCheckOutline,
    'mdi-clipboard-list-outline': mdiClipboardListOutline,
    'mdi-clock-alert-outline': mdiClockAlertOutline,
    'mdi-clock-outline': mdiClockOutline,
    'mdi-clock-remove-outline': mdiClockRemoveOutline,
    'mdi-close': mdiClose,
    'mdi-close-circle': mdiCloseCircle,
    'mdi-close-circle-outline': mdiCloseCircleOutline,
    'mdi-cloud-sync-outline': mdiCloudSyncOutline,
    'mdi-cloud-upload-outline': mdiCloudUploadOutline,
    'mdi-cog': mdiCog,
    'mdi-cog-off-outline': mdiCogOffOutline,
    'mdi-cog-outline': mdiCogOutline,
    'mdi-cog-transfer-outline': mdiCogTransferOutline,
    'mdi-compare': mdiCompare,
    'mdi-compare-remove': mdiCompareRemove,
    'mdi-content-copy': mdiContentCopy,
    'mdi-content-duplicate': mdiContentDuplicate,
    'mdi-content-save-outline': mdiContentSaveOutline,
    'mdi-cookie-cog-outline': mdiCookieCogOutline,
    'mdi-cookie-outline': mdiCookieOutline,
    'mdi-cpu-64-bit': mdiCpu64Bit,
    'mdi-crane': mdiCrane,
    'mdi-credit-card-off-outline': mdiCreditCardOffOutline,
    'mdi-credit-card-outline': mdiCreditCardOutline,
    'mdi-crown': mdiCrown,
    'mdi-crown-outline': mdiCrownOutline,
    'mdi-currency-usd': mdiCurrencyUsd,
    'mdi-database-check-outline': mdiDatabaseCheckOutline,
    'mdi-database-search-outline': mdiDatabaseSearchOutline,
    'mdi-delete-alert-outline': mdiDeleteAlertOutline,
    'mdi-delete-outline': mdiDeleteOutline,
    'mdi-diamond-outline': mdiDiamondOutline,
    'mdi-domain': mdiDomain,
    'mdi-dots-horizontal-circle': mdiDotsHorizontalCircle,
    'mdi-dots-horizontal-circle-outline': mdiDotsHorizontalCircleOutline,
    'mdi-dots-vertical': mdiDotsVertical,
    'mdi-download-outline': mdiDownloadOutline,
    'mdi-drag': mdiDrag,
    'mdi-earth': mdiEarth,
    'mdi-email-alert-outline': mdiEmailAlertOutline,
    'mdi-email-arrow-right-outline': mdiEmailArrowRightOutline,
    'mdi-email-check-outline': mdiEmailCheckOutline,
    'mdi-email-fast-outline': mdiEmailFastOutline,
    'mdi-email-mark-as-unread': mdiEmailMarkAsUnread,
    'mdi-email-outline': mdiEmailOutline,
    'mdi-email-sync-outline': mdiEmailSyncOutline,
    'mdi-engine-off': mdiEngineOff,
    'mdi-engine-off-outline': mdiEngineOffOutline,
    'mdi-engine-outline': mdiEngineOutline,
    'mdi-excavator': mdiExcavator,
    'mdi-exit-run': mdiExitRun,
    'mdi-eye-off-outline': mdiEyeOffOutline,
    'mdi-eye-outline': mdiEyeOutline,
    'mdi-facebook': mdiFacebook,
    'mdi-facebook-messenger': mdiFacebookMessenger,
    'mdi-factory': mdiFactory,
    'mdi-file-alert-outline': mdiFileAlertOutline,
    'mdi-file-code-outline': mdiFileCodeOutline,
    'mdi-file-document-outline': mdiFileDocumentOutline,
    'mdi-file-outline': mdiFileOutline,
    'mdi-file-pdf-box': mdiFilePdfBox,
    'mdi-file-search-outline': mdiFileSearchOutline,
    'mdi-file-video-outline': mdiFileVideoOutline,
    'mdi-filter-remove-outline': mdiFilterRemoveOutline,
    'mdi-filter-variant': mdiFilterVariant,
    'mdi-fire': mdiFire,
    'mdi-flag': mdiFlag,
    'mdi-flag-off-outline': mdiFlagOffOutline,
    'mdi-flag-outline': mdiFlagOutline,
    'mdi-forklift': mdiForklift,
    'mdi-form-select': mdiFormSelect,
    'mdi-format-list-bulleted': mdiFormatListBulleted,
    'mdi-format-list-checkbox': mdiFormatListCheckbox,
    'mdi-fuel': mdiFuel,
    'mdi-fullscreen': mdiFullscreen,
    'mdi-garage': mdiGarage,
    'mdi-gas-station-outline': mdiGasStationOutline,
    'mdi-gift-outline': mdiGiftOutline,
    'mdi-handshake-outline': mdiHandshakeOutline,
    'mdi-hard-hat': mdiHardHat,
    'mdi-headset': mdiHeadset,
    'mdi-heart': mdiHeart,
    'mdi-heart-outline': mdiHeartOutline,
    'mdi-help-circle-outline': mdiHelpCircleOutline,
    'mdi-history': mdiHistory,
    'mdi-home-outline': mdiHomeOutline,
    'mdi-identifier': mdiIdentifier,
    'mdi-image-multiple-outline': mdiImageMultipleOutline,
    'mdi-image-off-outline': mdiImageOffOutline,
    'mdi-image-outline': mdiImageOutline,
    'mdi-image-plus-outline': mdiImagePlusOutline,
    'mdi-image-search-outline': mdiImageSearchOutline,
    'mdi-image-size-select-large': mdiImageSizeSelectLarge,
    'mdi-information-outline': mdiInformationOutline,
    'mdi-instagram': mdiInstagram,
    'mdi-key-alert-outline': mdiKeyAlertOutline,
    'mdi-key-outline': mdiKeyOutline,
    'mdi-leaf': mdiLeaf,
    'mdi-lightbulb-on-outline': mdiLightbulbOnOutline,
    'mdi-lightbulb-outline': mdiLightbulbOutline,
    'mdi-lightning-bolt': mdiLightningBolt,
    'mdi-link-variant': mdiLinkVariant,
    'mdi-loading': mdiLoading,
    'mdi-lock-check-outline': mdiLockCheckOutline,
    'mdi-lock-open-outline': mdiLockOpenOutline,
    'mdi-lock-outline': mdiLockOutline,
    'mdi-lock-reset': mdiLockReset,
    'mdi-login': mdiLogin,
    'mdi-logout': mdiLogout,
    'mdi-magnify': mdiMagnify,
    'mdi-magnify-close': mdiMagnifyClose,
    'mdi-map-marker': mdiMapMarker,
    'mdi-map-marker-off-outline': mdiMapMarkerOffOutline,
    'mdi-map-marker-outline': mdiMapMarkerOutline,
    'mdi-map-outline': mdiMapOutline,
    'mdi-map-search-outline': mdiMapSearchOutline,
    'mdi-message-off-outline': mdiMessageOffOutline,
    'mdi-message-outline': mdiMessageOutline,
    'mdi-message-text-outline': mdiMessageTextOutline,
    'mdi-minus-circle-outline': mdiMinusCircleOutline,
    'mdi-molecule-co2': mdiMoleculeCo2,
    'mdi-monitor-speaker': mdiMonitorSpeaker,
    'mdi-motorbike': mdiMotorbike,
    'mdi-music-note': mdiMusicNote,
    'mdi-numeric': mdiNumeric,
    'mdi-office-building-outline': mdiOfficeBuildingOutline,
    'mdi-open-in-new': mdiOpenInNew,
    'mdi-package-variant-closed': mdiPackageVariantClosed,
    'mdi-palette-outline': mdiPaletteOutline,
    'mdi-pencil': mdiPencil,
    'mdi-pencil-outline': mdiPencilOutline,
    'mdi-phone': mdiPhone,
    'mdi-phone-alert-outline': mdiPhoneAlertOutline,
    'mdi-phone-check-outline': mdiPhoneCheckOutline,
    'mdi-phone-outline': mdiPhoneOutline,
    'mdi-pin': mdiPin,
    'mdi-pin-off': mdiPinOff,
    'mdi-plus': mdiPlus,
    'mdi-plus-circle-outline': mdiPlusCircleOutline,
    'mdi-qrcode': mdiQrcode,
    'mdi-receipt-outline': mdiReceiptOutline,
    'mdi-receipt-text-check-outline': mdiReceiptTextCheckOutline,
    'mdi-receipt-text-outline': mdiReceiptTextOutline,
    'mdi-record-circle-outline': mdiRecordCircleOutline,
    'mdi-refresh': mdiRefresh,
    'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
    'mdi-rv-truck': mdiRvTruck,
    'mdi-sail-boat': mdiSailBoat,
    'mdi-seat-passenger': mdiSeatPassenger,
    'mdi-seat-recline-extra': mdiSeatReclineExtra,
    'mdi-send': mdiSend,
    'mdi-send-outline': mdiSendOutline,
    'mdi-shape-outline': mdiShapeOutline,
    'mdi-shape-plus-outline': mdiShapePlusOutline,
    'mdi-share-outline': mdiShareOutline,
    'mdi-share-variant-outline': mdiShareVariantOutline,
    'mdi-shield-account-outline': mdiShieldAccountOutline,
    'mdi-shield-alert-outline': mdiShieldAlertOutline,
    'mdi-shield-car': mdiShieldCar,
    'mdi-shield-check': mdiShieldCheck,
    'mdi-shield-check-outline': mdiShieldCheckOutline,
    'mdi-shield-crown': mdiShieldCrown,
    'mdi-shield-outline': mdiShieldOutline,
    'mdi-shield-search': mdiShieldSearch,
    'mdi-shield-star-outline': mdiShieldStarOutline,
    'mdi-ski-water': mdiSkiWater,
    'mdi-sort': mdiSort,
    'mdi-speedometer': mdiSpeedometer,
    'mdi-speedometer-medium': mdiSpeedometerMedium,
    'mdi-spray': mdiSpray,
    'mdi-star': mdiStar,
    'mdi-star-check-outline': mdiStarCheckOutline,
    'mdi-star-off-outline': mdiStarOffOutline,
    'mdi-star-outline': mdiStarOutline,
    'mdi-store-outline': mdiStoreOutline,
    'mdi-swap-horizontal': mdiSwapHorizontal,
    'mdi-sync': mdiSync,
    'mdi-tag': mdiTag,
    'mdi-tag-multiple-outline': mdiTagMultipleOutline,
    'mdi-tag-off-outline': mdiTagOffOutline,
    'mdi-tag-outline': mdiTagOutline,
    'mdi-text-box-outline': mdiTextBoxOutline,
    'mdi-text-box-remove-outline': mdiTextBoxRemoveOutline,
    'mdi-text-long': mdiTextLong,
    'mdi-text-search': mdiTextSearch,
    'mdi-ticket-outline': mdiTicketOutline,
    'mdi-ticket-percent-outline': mdiTicketPercentOutline,
    'mdi-timer-outline': mdiTimerOutline,
    'mdi-tire': mdiTire,
    'mdi-tractor': mdiTractor,
    'mdi-transit-connection-variant': mdiTransitConnectionVariant,
    'mdi-translate': mdiTranslate,
    'mdi-trash-can-outline': mdiTrashCanOutline,
    'mdi-trending-down': mdiTrendingDown,
    'mdi-trending-up': mdiTrendingUp,
    'mdi-trophy-outline': mdiTrophyOutline,
    'mdi-truck': mdiTruck,
    'mdi-truck-delivery': mdiTruckDelivery,
    'mdi-truck-outline': mdiTruckOutline,
    'mdi-truck-trailer': mdiTruckTrailer,
    'mdi-tune-variant': mdiTuneVariant,
    'mdi-twitter': mdiTwitter,
    'mdi-unfold-less-horizontal': mdiUnfoldLessHorizontal,
    'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
    'mdi-upload': mdiUpload,
    'mdi-van-utility': mdiVanUtility,
    'mdi-view-dashboard-outline': mdiViewDashboardOutline,
    'mdi-warehouse': mdiWarehouse,
    'mdi-web': mdiWeb,
    'mdi-weight': mdiWeight,
    'mdi-whatsapp': mdiWhatsapp,
    'mdi-wifi-off': mdiWifiOff,
    'mdi-wrench': mdiWrench,
    'mdi-wrench-clock': mdiWrenchClock,
    'mdi-wrench-outline': mdiWrenchOutline,
    'mdi-youtube': mdiYoutube,
}

/** Zastepcza ikona, gdy backend przysle nazwe spoza mapy - lepsza niz pusty kwadrat. */
export const MDI_FALLBACK = MDI_PATHS['mdi-help-circle-outline'] ?? ''
